# escape=`

# This file is auto-generated by PostSharp.Engineering.

FROM mcr.microsoft.com/windows/servercore:ltsc2025

# The initial shell is PowerShell Desktop.
SHELL ["powershell", "-Command"]

# Prepare environment
ENV PSExecutionPolicyPreference=Bypass
ENV POWERSHELL_UPDATECHECK=FALSE
ENV TEMP=C:\Temp
ENV TMP=C:\Temp
ENV RUNNING_IN_DOCKER=TRUE

# Enable long path support
RUN Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1



# Install Git
RUN Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.50.0.windows.1/MinGit-2.50.0-64-bit.zip -OutFile MinGit.zip; `
    Expand-Archive c:\\MinGit.zip -DestinationPath C:\\git; `
    Remove-Item C:\\MinGit.zip; `
    $pathsToAdd = @('C:\git\cmd', 'C:\git\bin', 'C:\git\usr\bin'); `
    $newPath = [Environment]::GetEnvironmentVariable('PATH', 'Machine') + ';' + ($pathsToAdd -join ';'); `
    [Environment]::SetEnvironmentVariable('PATH', $newPath, 'Machine');


# Install PowerShell 7
RUN Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.5.2/PowerShell-7.5.2-win-x64.msi -OutFile PowerShell.msi; `
    $process = Start-Process msiexec.exe -Wait -PassThru -ArgumentList '/I PowerShell.msi /quiet'; `
    if ($process.ExitCode -ne 0) { exit $process.ExitCode }; `
    Remove-Item PowerShell.msi; `
    $pathsToAdd = @('C:\Program Files\PowerShell\7'); `
    $newPath = [Environment]::GetEnvironmentVariable('PATH', 'Machine') + ';' + ($pathsToAdd -join ';'); `
    [Environment]::SetEnvironmentVariable('PATH', $newPath, 'Machine');


# Download .NET Installer
RUN Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1; `
    $pathsToAdd = @('C:\Program Files\dotnet'); `
    $newPath = [Environment]::GetEnvironmentVariable('PATH', 'Machine') + ';' + ($pathsToAdd -join ';'); `
    [Environment]::SetEnvironmentVariable('PATH', $newPath, 'Machine'); 


# Install .NET Sdk 9.0.205
RUN powershell -ExecutionPolicy Bypass -File dotnet-install.ps1 -Version 9.0.205 -InstallDir 'C:\Program Files\dotnet'; 


# Epilogue
# Create directories for mountpoints
ARG MOUNTPOINTS
RUN if ($env:MOUNTPOINTS) { `
        $mounts = $env:MOUNTPOINTS -split ';'; `
        foreach ($dir in $mounts) { `
            if ($dir) { `
                Write-Host "Creating directory $dir`."; `
                New-Item -ItemType Directory -Path $dir -Force | Out-Null; `
            } `
        } `
    }

# Import environment variables
COPY ReadEnvironmentVariables.ps1 c:\ReadEnvironmentVariables.ps1    
COPY env.g.json c:\env.g.json
RUN c:\ReadEnvironmentVariables.ps1 c:\env.g.json   

# Configure NuGet
ENV NUGET_PACKAGES=c:\packages

# Configure .NET SDK
ENV DOTNET_NOLOGO=1

# Configure git
ARG SRC_DIR
RUN git config --global --add safe.directory $env:SRC_DIR/; `
    git config --global user.name $env:GIT_USER_NAME; `
    git config --global user.email $env:GIT_USER_EMAIL;
