using Microsoft.Extensions.DependencyInjection;
namespace Metrics
{
  public static class MetricRegistrations
  {
    public static void AddAutoGeneratedMetrics(this ServiceCollection serviceCollection)
    {
      serviceCollection.AddSingleton(typeof(HatShopMetrics));
    }
  }
}