
<Project>

    <PropertyGroup>
        <MetalamaCompilerVersion>2025.2.3-rc</MetalamaCompilerVersion>
        <MetalamaVersion>2025.2.5-rc</MetalamaVersion>
        <MetalamaPremiumVersion>2025.2.5-rc</MetalamaPremiumVersion>
    <MetalamaSamplesReleaseVersion>2025.2.5-rc</MetalamaSamplesReleaseVersion><MetalamaSamplesReleaseMainVersion>2025.2.5</MetalamaSamplesReleaseMainVersion></PropertyGroup>

</Project>