# escape=`

# This file is auto-generated by PostSharp.Engineering.

ARG BASE_IMAGE=build.Dockerfile
FROM ${BASE_IMAGE}

# The base image's shell is Windows PowerShell (use full path to avoid HCS issues)
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]



# Install Node.js
RUN Invoke-WebRequest -Uri "https://nodejs.org/dist/v22.0.0/node-v22.0.0-win-x64.zip" -OutFile node.zip; `
    Expand-Archive node.zip -DestinationPath C:\; `
    Rename-Item "C:\node-v22.0.0-win-x64" "C:\nodejs"; `
    Remove-Item node.zip

ENV NPM_CONFIG_PREFIX=C:\npm
ENV PATH="C:\nodejs;C:\npm;${PATH}"
