# escape=`

# This file is auto-generated by PostSharp.Engineering.

ARG BASE_IMAGE=claude-pre.Dockerfile
FROM ${BASE_IMAGE}

# The base image's shell is Windows PowerShell (use full path to avoid HCS issues)
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]



# Timestamp
# Cache invalidation layer - changes when -Update is used
COPY .g/update.timestamp C:\docker-context\update.timestamp
RUN Write-Host "PostSharp.Engineering build timestamp: $(Get-Content C:\docker-context\update.timestamp)"


# Install Claude CLI
# Set HOME/USERPROFILE so Claude CLI finds credentials during build
ENV HOME=C:\\Users\\ContainerAdministrator
ENV USERPROFILE=C:\\Users\\ContainerAdministrator

# Install Claude CLI and configure using cmd shell to avoid HCS issues with PowerShell
SHELL ["cmd", "/S", "/C"]
RUN C:\nodejs\npm.cmd install --global @anthropic-ai/claude-code@latest
RUN mkdir C:\Users\ContainerAdministrator\.claude && echo {"hasCompletedOnboarding": true} > C:\Users\ContainerAdministrator\.claude.json && echo {"alwaysThinkingEnabled": true, "spinnerTipsEnabled": false} > C:\Users\ContainerAdministrator\.claude\settings.json

# Restore PowerShell shell using full path
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]


# Install Claude CLI Add-ins
# Install Claude plugins using cmd shell to avoid HCS issues with PowerShell
SHELL ["cmd", "/S", "/C"]
RUN echo Installing Claude plugins && C:\npm\claude plugin marketplace add https://github.com/metalama/Metalama.AI.Skills && C:\npm\claude plugin marketplace add https://github.com/postsharp/PostSharp.Engineering.AISkills && C:\npm\claude plugin install metalama && C:\npm\claude plugin install metalama-dev && C:\npm\claude plugin install eng

# Restore PowerShell shell using full path
SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-Command"]
