using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using Microsoft.Extensions.DependencyInjection;

namespace Metalama.Samples.Metrics;

public class GenerateAddMetricsExtensionAttribute : CompilationAspect
{
    public override void BuildAspect( IAspectBuilder<ICompilation> builder )
    {
        var type = builder
            .WithNamespace( "Metrics" )
            .IntroduceClass(
                "MetricRegistrations",
                buildType: t =>
                {
                    t.IsStatic = true;
                    t.Accessibility = Accessibility.Public;
                } );

        type.IntroduceMethod( nameof(AddAutoGeneratedMetrics) );
    }

    [Template]
    public static void AddAutoGeneratedMetrics( [This] ServiceCollection serviceCollection )
    {
        foreach ( var annotation in meta.Target.Compilation.Enhancements().GetAnnotations<MetricTypeAnnotation>() )
        {
            var targetType = annotation.MetricType.GetTarget();
            serviceCollection.AddSingleton( (Type) targetType.ToTypeOfExpression().Value! );
        }
    }
}