<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <NoWarn>SA0001;CS8002;SA1114;SA1115</NoWarn>
        <!-- Disable warnings about vulnerabilities in transitive dependencies. -->
        <!-- This is generally okay, since this code does not interact with users. -->
        <NoWarn>$(NoWarn);NU1903;NU1904</NoWarn>
        <SampleProjectKind>Regular</SampleProjectKind>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PostSharp.Engineering.BuildTools" />
    </ItemGroup>

</Project>
